### PR TITLE
include css file, update README for lab support

### PR DESCRIPTION
**Pull request by timkpaine**

### CODE REVIEW

**Comment by timkpaine** [comment]
pls ping me your npm username

**Comment by kuk** [comment]
Thank you very much! Currently we have no npm account. Do you think we need to upload ipyannotate there?

**Comment by timkpaine** [comment]
I just did before, it is [here](https://www.npmjs.com/package/ipyannotate), I can transfer ownership to you. 

Thanks for this package, its is awesome!. I can deprecate something I started to work on but never finished ([this](https://github.com/timkpaine/nannotate)).

**Comment by kuk** [comment]
Created an account https://www.npmjs.com/~alexkuk

**Pull request merged**
