### PR TITLE
Feature Idea: on_click callbacks

### PR DESCRIPTION
**Pull request by timkpaine**
I was working on a 6th example for sentiment analysis, and realized I needed a way of modifying the tasks so that you can get instant feedback. So I added a little bit of code that can hook into the buttons and lets you modify the tasks. In this example, I modify my sentiment, which you can see in the gif below:

tmp

Let me know what you think.

### CODE REVIEW

**Comment by timkpaine** [comment]
can see example https://github.com/timkpaine/ipyannotate-examples/blob/master/06_sent/notes.ipynb

**Comment by kuk** [comment]
It is a good idea.

I suggest to make interface similar to standart `widget.Button` https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Events.html#Example 
1. Rename `on_click_custom` -> `callback`
2. Remove `on_click_custom` argument from `__init__` (optional, not sure)
3. Add `def on_click(self, callback): self.callback = callback`
4. Change argument from `task` to `button`, same as in `widget.Button` . Then `handle_click` in yout example would be:
```
def handle_click(button):
  task = button.annotation.tasks.current
  ...

of just

def handle_click(_):
  task = annotation.tasks.current  # annotation from global context
 ```

**Comment by timkpaine** [comment]
ok I did 1, 3, and 4. For 2, what do you mean by this?

**Comment by timkpaine** [comment]
code looks like [this](https://github.com/timkpaine/ipyannotate-examples/blob/master/06_sent/notes.ipynb) now

**Comment by kuk** [comment]
Did some refactoring https://github.com/natasha/ipyannotate/commit/0e943b94342da7ff9bc20ea1e5d5efcc9f5d05d4 . Eventually decided on 2. Without callback argument in `__init__` code is a bit clearer. 

Code in your examples https://github.com/natasha/ipyannotate-examples/blob/master/06_sent/notes.ipynb changes from

```
pos = Button(label='+', shortcut='1', value=1, color='green', icon='', callback=handle_click),
neu = Button(label='o', shortcut='2', value=0, color='gray', icon='', callback=handle_click),
neg = Button(label='-', shortcut='3', value=-1, color='red', icon='', callback=handle_click)
```

to 
```

pos = Button(label='+', shortcut='1', value=1, color='green', icon=''),
neu = Button(label='o', shortcut='2', value=0, color='gray', icon=''),
neg = Button(label='-', shortcut='3', value=-1, color='red', icon='')

for button in [pos, neu, neg]:
    button.on_click(callback)

```

**Comment by timkpaine** [comment]
looks good, thanks!

**Pull request merged**
